version: "2.1"
services:
  steve_api:
    container_name: steve_api
    build:
      context: ./api
    ports:
      - "5000:5000"
    environment:
      - DEBUG=True
  steve_dispatcher:
    container_name: steve_dispatcher
    build:
      context: ./dispatcher
    ports:
      - "5001:5000"
    environment:
      - DEBUG=True
  steve_jobs_store:
    container_name: steve_jobs_store
    build:
      context: ./jobs_store
    ports:
      - "5002:5000"
    environment:
      - DEBUG=True
  steve_scheduler:
    container_name: steve_scheduler
    build:
      context: ./scheduler
    ports:
      - "5003:5000"
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/jobs_test
  # steve_jobs_db:
  #   container_name: steve_jobs_db
  #   build:
  #     context: ./db
  #   ports:
  #       - 5004:5000
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   healthcheck:
  #     test: exit 0
